// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3ezyvcOOizcxXod727hEAy6cG8FfRMCU',
    appId: '1:729553550400:android:9cf0c6db595ad89901f3a5',
    messagingSenderId: '729553550400',
    projectId: 'eduplay-8792f',
    storageBucket: 'eduplay-8792f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZsCiKQJhQ2fvWTTTy2Txxuy1R6Ak9BEI',
    appId: '1:729553550400:ios:4480b23f2ab981e101f3a5',
    messagingSenderId: '729553550400',
    projectId: 'eduplay-8792f',
    storageBucket: 'eduplay-8792f.firebasestorage.app',
    iosBundleId: 'com.example.eduPlay',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3iyJW0cffV7lIe2bR88KqxrMaBUuJZxk',
    appId: '1:729553550400:web:dfff11b6e7dc86f301f3a5',
    messagingSenderId: '729553550400',
    projectId: 'eduplay-8792f',
    authDomain: 'eduplay-8792f.firebaseapp.com',
    storageBucket: 'eduplay-8792f.firebasestorage.app',
    measurementId: 'G-0GQCJB4X0X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZsCiKQJhQ2fvWTTTy2Txxuy1R6Ak9BEI',
    appId: '1:729553550400:ios:4480b23f2ab981e101f3a5',
    messagingSenderId: '729553550400',
    projectId: 'eduplay-8792f',
    storageBucket: 'eduplay-8792f.firebasestorage.app',
    iosBundleId: 'com.example.eduPlay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3iyJW0cffV7lIe2bR88KqxrMaBUuJZxk',
    appId: '1:729553550400:web:e5a66561d6c5a17201f3a5',
    messagingSenderId: '729553550400',
    projectId: 'eduplay-8792f',
    authDomain: 'eduplay-8792f.firebaseapp.com',
    storageBucket: 'eduplay-8792f.firebasestorage.app',
    measurementId: 'G-DKQPVG46XM',
  );

}